### ISSUE TITLE
BLUE_BACK 404 because of toUpperCase

### ISSUE THREAD

**Issue by simo1994** [richardschneider/cardsJS#18]
I've found a problem when using 'Blue_Back' using a knockout binding.
This line of code in cards.js: `name = cards[i].toString().toUpperCase();`
makes so that the unexisting file 'BLUE_BACK.svg' gets included instead of 'Blue_Back.svg'

This becomes a problem when using on HTTP instead of local file:///.

**Comment by richardschneider** [comment]
Good catch!  I'll fix it soon.

**Comment by simo1994** [comment]
Thanks for the quick fix. If you could also update the version number so we can use the CDN hosted script it would be magnificent.
